# select Ubuntu Linux image
FROM ubuntu:latest
# Use the 'apt-get' system to install figlet
RUN apt-get update && apt-get install -y figlet
# set the working_dir/
RUN mkdir /working_dir
WORKDIR /working_dir
